/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable import/extensions */
/* eslint-disable import/no-unresolved */
/* eslint-disable no-undef */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.css';
import React from 'react';
import MusicBar from './components/Musicbar/Musicbar';
import NavigationBar from './components/NavBar/NavigationBar';
import QueryProviders from './components/QueryProvider/QueryProvider';
import { SharedAudioProvider } from './components/audio/Audio';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'DreamVault',
  description: 'Generated by 별이 빛나는 밤',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css"
          rel="stylesheet"
        />
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
      </head>
      <body className={`${inter.className} flex w-full flex-row`}>
        <link
          rel="icon"
          href="https://i.ibb.co/1GnSm8z/Dream-Vault-Png.png"
          sizes="any"
        />
        <QueryProviders>
          <SharedAudioProvider>
            <NavigationBar />
            <div className="main-content">
              {children}
              <MusicBar />
            </div>
          </SharedAudioProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
